spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 423061564210-pne80qttftla0khcrp07pv619ll27fcj.apps.googleusercontent.com
            client-secret: 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
          git-hub:
            client-id: 47ad5796be4315d91825
            client-secret: c9d79006aefccf898d8fbcaa6fb998dde5f63e12

