spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 423061564210-pne80qttftla0khcrp07pv619ll27fcj.apps.googleusercontent.com
            clientSecret: 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
