#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            dclientId: 423061564210-pne80qttftla0khcrp07pv619ll27fcj.apps.googleusercontent.com
#            dclientSecret: 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
