spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 423061564210-pne80qttftla0khcrp07pv619ll27fcj.apps.googleusercontent.com
            client-secret: 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
          git-hub:
            client-id: 47ad5796be4315d91825
            client-secret: c9d79006aefccf898d8fbcaa6fb998dde5f63e12
          facebook:
            client-id: 747797897517794
            client-secret: 8a574b0021782f429c07301197f99e1f
            scope:
              - email
              - public_profile
application:
  security:
    jwt:
      secret-key: "357638792F423F4428472B4B6250655368566D597133743677397A2443264629"
      expiration: 86400000
      refresh-token:
        expiration: 604800000

  datasource:
    tomcat:
      max-active: 1
  session:
    store-type: none
    timeout: 86400
  redis:
    host: 172.22.64.1
    port: 6379
  filters:
    - name: RequestRateLimiter
      args:
        redis-rate-limiter.replenishRate: 20
        redis-rate-limiter.burstCapacity: 40
        redis-rate-limiter.requestedTokens: 1
